/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotesImport } from './routes/notes'
import { Route as IndexImport } from './routes/index'
import { Route as NotesIndexImport } from './routes/notes.index'

// Create Virtual Routes

const SettingsLazyImport = createFileRoute('/settings')()
const NotesNoteIdLazyImport = createFileRoute('/notes/$noteId')()

// Create/Update Routes

const SettingsLazyRoute = SettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const NotesRoute = NotesImport.update({
  path: '/notes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NotesIndexRoute = NotesIndexImport.update({
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)

const NotesNoteIdLazyRoute = NotesNoteIdLazyImport.update({
  path: '/$noteId',
  getParentRoute: () => NotesRoute,
} as any).lazy(() => import('./routes/notes.$noteId.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdLazyImport
      parentRoute: typeof NotesImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexImport
      parentRoute: typeof NotesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  NotesRoute: NotesRoute.addChildren({ NotesNoteIdLazyRoute, NotesIndexRoute }),
  SettingsLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/notes",
        "/settings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/notes": {
      "filePath": "notes.tsx",
      "children": [
        "/notes/$noteId",
        "/notes/"
      ]
    },
    "/settings": {
      "filePath": "settings.lazy.tsx"
    },
    "/notes/$noteId": {
      "filePath": "notes.$noteId.lazy.tsx",
      "parent": "/notes"
    },
    "/notes/": {
      "filePath": "notes.index.tsx",
      "parent": "/notes"
    }
  }
}
ROUTE_MANIFEST_END */
