export enum AppRoutes {
  Root = "/",
  New = "/new",
  // GoPremium = "/get-premium",
  // Account = "/account",
  Notes = "/notes",
  // Search = "/search",
  NoteById = "/notes/:id",
  Help = "/help",
  Changelog = "/changelog",
  Settings = "/settings",
  SettingsWelcomeMessage = "/welcome-message",
  // Feedback = "/feedback",
  NotFound = "/not-found",
}
