/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoteWelcomeRouteImport } from './routes/note.welcome'
import { Route as NoteNewRouteImport } from './routes/note.new'
import { Route as NoteNoteIdRouteImport } from './routes/note.$noteId'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppChangelogRouteImport } from './routes/app.changelog'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteWelcomeRoute = NoteWelcomeRouteImport.update({
  id: '/note/welcome',
  path: '/note/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteNewRoute = NoteNewRouteImport.update({
  id: '/note/new',
  path: '/note/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteNoteIdRoute = NoteNoteIdRouteImport.update({
  id: '/note/$noteId',
  path: '/note/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/app/help',
  path: '/app/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChangelogRoute = AppChangelogRouteImport.update({
  id: '/app/changelog',
  path: '/app/changelog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/app/changelog': typeof AppChangelogRoute
  '/app/help': typeof AppHelpRoute
  '/app/settings': typeof AppSettingsRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/note/new': typeof NoteNewRoute
  '/note/welcome': typeof NoteWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/app/changelog': typeof AppChangelogRoute
  '/app/help': typeof AppHelpRoute
  '/app/settings': typeof AppSettingsRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/note/new': typeof NoteNewRoute
  '/note/welcome': typeof NoteWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/app/changelog': typeof AppChangelogRoute
  '/app/help': typeof AppHelpRoute
  '/app/settings': typeof AppSettingsRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/note/new': typeof NoteNewRoute
  '/note/welcome': typeof NoteWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/app/changelog'
    | '/app/help'
    | '/app/settings'
    | '/note/$noteId'
    | '/note/new'
    | '/note/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/app/changelog'
    | '/app/help'
    | '/app/settings'
    | '/note/$noteId'
    | '/note/new'
    | '/note/welcome'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/app/changelog'
    | '/app/help'
    | '/app/settings'
    | '/note/$noteId'
    | '/note/new'
    | '/note/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AppChangelogRoute: typeof AppChangelogRoute
  AppHelpRoute: typeof AppHelpRoute
  AppSettingsRoute: typeof AppSettingsRoute
  NoteNoteIdRoute: typeof NoteNoteIdRoute
  NoteNewRoute: typeof NoteNewRoute
  NoteWelcomeRoute: typeof NoteWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/welcome': {
      id: '/note/welcome'
      path: '/note/welcome'
      fullPath: '/note/welcome'
      preLoaderRoute: typeof NoteWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/new': {
      id: '/note/new'
      path: '/note/new'
      fullPath: '/note/new'
      preLoaderRoute: typeof NoteNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$noteId': {
      id: '/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof NoteNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/help': {
      id: '/app/help'
      path: '/app/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/changelog': {
      id: '/app/changelog'
      path: '/app/changelog'
      fullPath: '/app/changelog'
      preLoaderRoute: typeof AppChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AppChangelogRoute: AppChangelogRoute,
  AppHelpRoute: AppHelpRoute,
  AppSettingsRoute: AppSettingsRoute,
  NoteNoteIdRoute: NoteNoteIdRoute,
  NoteNewRoute: NoteNewRoute,
  NoteWelcomeRoute: NoteWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
